# Anexo. 3 Tablas {.unnumbered}

```{r}
#| output: asis
#| echo: false

ITX <- read.csv('../data/ITX.MC.csv')
ITX <- head(ITX)
cat(md_table(ITX))
```

: Estructura de datos de precios {#tbl-pre_estruc}

::: figure-caption
Elaboración propia: Mediante el uso de RStudio con la base de datos histórico de "INDITEX", obtenida de https://finance.yahoo.com/, en el periodo comprendido entre el 24-05-2001 al 31-05-2001.
:::

::: {style="font-size:12px"}
```{r}
#| output: asis
#| echo: false

empresast <- empresas |>
  mutate(
    Seleccionadas = if_else(is.element(TICKERS,names(returns_emps3)),"X",""),
    MERCADO = "MC",
    INDICE = gsub("IBEX TOP Dividendo","IBEXTD",INDICE)
  )
cat(md_table(empresast))
```

: Lista de empresas cotizadas {#tbl-emp_cotiz}
:::

::: figure-caption Obtenido de: La información expuesta en el sitio oficial de Bolsas y Mercados españoles, @BMEexcha. *Nota:* MC en MERCADO significa Mercado Continuo, IBEXTD en INDICE significa IBEX TOP Dividendo. :::

```{r}
#| output: asis
#| echo: false

entradas <- c(1,2,3)
obs <- sapply(returns_indc, function(x){
  dim(x)[1]
})
obs <- sum(obs)
emps_n <- length(returns_indc)
muestras <- data.frame(
  Entradas = entradas,
  `Muestras totales` = (obs-((entradas-1+1)*emps_n))
)
cat(md_table(muestras))
```

: Cantidades de muestras utilizadas para entrenar los modelos {#tbl-muestras}

::: figure-caption
Obtenido de: La información expuesta en el sitio oficial de Bolsas y Mercados españoles, @BMEexcha.
:::

```{r}
#| output: asis
#| echo: false
#| label: tbl-indicadores
#| tbl-cap: >
#|   Mejores y peroes empresas según los resultados obtenidos de los cálculos de los indicadores

for (i in 1:3) {
  listresult <- get(paste0("resultscnnlstmssing",i))
  data <- do.call(rbind,listresult$resultsID)
  data <- data |>
    group_by(ID) |>
    summarize(
      rsqrd = mean(rsqrd),
      mse= mean(mse)) |>
    ungroup() |>
    arrange(desc(rsqrd))
  assign(
    paste0("data",i,"h"),
    head(data,10)
    )
  assign(
    paste0("data",i,"t"),
    tail(data,10)
    )
  assign(
    paste0("data",i),
    rbind(
      get(paste0("data",i,"h")),
      get(paste0("data",i,"t")))
    )
  dfnames <- get(paste0("data",i))
  names(dfnames) <- c("TICKER","R<sup>2</sup>","MSE")
  assign(
    paste0("data",i),
    dfnames)
  if(i==3){
    table <- cbind(data1,data2,data3)
  }
}

table <- kable(table, format = "html", escape = F)
table <- table |>
  kable_styling(bootstrap_options = "striped") |>
  add_header_above(c("1" = 3, "2" = 3, "3" = 3))

table
```

::: figure-caption
Elaboración propia.
:::
