# Thanks {.unnumbered}

I want to express my sincere gratitude to all the people who contributed significantly to the completion of this final master's thesis. Without your support, guidance and encouragement, this achievement would not have been possible.

I would like to thank the Xunta de Galica for providing me with the resources to carry out master's studies as a beneficiary of the Excellence Juventud Exterior Scholarship.

I would like to thank Universidade da Coruña for the knowledge acquired while studying the Master's Degree in Banking and Finance. His commitment to academic excellence has been a constant source of inspiration.

I am deeply grateful to my tutor Xosé Manuel Martínez Filgueira for his expert guidance and valuable suggestions throughout this process. Their knowledge and dedication were essential to give direction and quality to this work.

My thanks are extended to my classmates and friends who provided a space for rich discussions and valuable contributions that contributed to the development of this work.

I also want to express my gratitude to my family for their constant emotional support and understanding during the challenging moments of this academic process.
