project:
  type: book

book:
  cover-image: udclogo.png
  title: "Trabajo Final de Máster"
  subtitle: "Titulo a definir"
  author: 
    - name: David Díaz Rodríguez
      affiliations:
        - id: udc
          name: Universidad de La Coruña 
          city: La Coruña
          state: Galicia
      orcid: https://orcid.org/0000-0002-0927-9795
      email: david.diazr@udc.es
    - name: Xosé Manuel Martínez Filgueira
      affiliations:
        - ref: udc
      orcid: https://orcid.org/0000-0003-2452-4864
      email: xose.martinez@udc.es
    - name: Ramón Miñones Crespo
      affiliations:
        - ref: udc
      email: ramon.minones@udc.es
  date: "11/2/2023"
  search: true
  repo-url: https://github.com/davidrsch/TFM
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter]
  page-navigation: true
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter1a.qmd
    - chapter2.qmd
    - chapter2a.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#D60D8C"
    fig-cap-location: top
    df-print: paged
    css: my_style.css
    lang:
      es
 #   language: 
#      lang/custom.yml
  pdf:
    documentclass: scrreprt
    template-partials: 
      - "template/before-body.tex"
      - "template/_titlepage.tex"
    include-in-header:
      - "template/in-header.tex"
  docx:
    reference-doc: referencia_formato.docx
    lang:
      es

editor: visual

