project:
  type: book

book:
  cover-image: udclogo.png
  title: "Trabajo Final de Máster"
  subtitle: "Titulo a definir"
  author: 
    - name: David Díaz Rodríguez
      affiliations:
        - id: udc
          name: Universidad de La Coruña 
          city: La Coruña
          state: Galicia
      orcid: https://orcid.org/0000-0002-0927-9795
      email: david.diazr@udc.es
    - name: Xosé Manuel Martínez Filgueira
      affiliations:
        - ref: udc
      orcid: https://orcid.org/0000-0003-2452-4864
      email: xose.martinez@udc.es
    - name: Ramón Miñones Crespo
      affiliations:
        - ref: udc
      email: ramon.minones@udc.es
  date: "11/2/2023"
  search: true
  repo-url: https://github.com/davidrsch/TFM
  repo-actions: [edit]
  downloads: [docx, pdf, epub]
  sharing: [twitter]
  page-navigation: true
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter1a.qmd
    - chapter2.qmd
    - chapter2a.qmd
    - references.qmd
  appendices:
    - Annex1.qmd
    - Annex2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#D60D8C"
    fig-cap-location: top
    df-print: paged
    css: my_style.css
    lang:
      es
 #   language: 
 #     lang/custom.yml
  pdf:
    documentclass: scrreprt
    papersize: letter
    highlight-style: github
    fig-cap-location: top
    fig-pos: H
    lang: 
      es
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
    
  docx:
    reference-doc: referencia_formato.docx
    lang:
      es

editor: visual

