# 3 Conclusiones {.unnumbered}

Durante el desarrollo de este trabajo, se ha abordado la aplicación de redes neuronales artificiales y programación cuadrática en la gestión de carteras financieras. A través de una cuidadosa caracterización de las series temporales financieras, se pudo comprender la importancia de analizar sus características y patrones para realizar pronósticos más precisos.

Se probaron distintas configuraciones de modelos de redes neuronales artificiales, conformadas por la combinación de capas convolucionales y LSTM, que diferían en la cantidad de observaciones históricas que usarían como entradas antes de realizarse una predicción. Las predicciones obtenidas a partir de los modelos antes mencionados se compararon con predicciones obtenidas mediante el uso de la media aritmética, que es uno de los indicadores que más comúnmente se utiliza. Como resultado de la comparación antes expuestas se obtuvo que los modelos en dependencia de la cantidad de observaciones que usaron como entradas: 1, 2 o 3; obtuvieron un R2 de: -0.00287, 0.0611 y 0.0179 respectivamente.

Las predicciones obtenidas, tanto con los modelos de RNA como con las medias aritméticas en conjunto con los comportamientos históricos fueron usados para, mediante el uso programación cuadrática, buscar la composición de carteras de menor riesgo. Tras la realización de una simulación de gestión de carteras se obtuvo que las carteras conformadas a partir de las predicciones de los modelos de RNA obtuvieron al final del periodo estudiado en comparación con las conformadas por las predicciones usando la media aritmética unas rentabilidades: 5.63% superior, para los modelos que usaron 1 observación como entrada; un 35.67% superior para los que usaron 2; y un 25.51% para los que usaron 3. Además, se observó que las carteras conformadas con los modelos de RNA obtuvieron unas rentabilidades superiores al índice, IBEX, en un 40.86%, 39.78% y 60.54%, para los modelos que usaron 1, 2 y 3 observaciones como entradas respectivamente.

Los resultados antes expuestos demuestran que el uso combinado de estas herramientas, las RNA y la programación cuadrática, pueden ofrecer una ventaja competitiva significativa en la gestión de sus activos financieros a empresas y organizaciones, permitiendo una toma de decisiones más efectiva, optimizando la composición de carteras y maximizando los rendimientos.

No obstante, es importante destacar que los resultados expuestos en el presente trabajo necesitan un estudio más profundo para analizar, entre otros aspectos, el peso que tienen los resultados de las predicciones de las distintas empresas en la composición de carteras. Por esta razón se considera el presente trabajo como el comienzo de una investigación más exhaustiva en la cual: se deben obtener datos de mayor calidad y se contrastará el uso de diversas técnicas, tanto para la obtención de las predicciones como para hallar la composición de cartera adecuada.
