# 3 Conclusions {.unnumbered}

During the development of this work, the application of artificial neural networks and quadratic programming in the management of financial portfolios has been addressed. Through a careful characterization of financial time series, it was possible to understand the importance of analyzing their characteristics and patterns to make more accurate forecasts.

Different configurations of artificial neural network models, made up of the combination of convolutional layers and LSTM, were tested, which differed in the number of historical observations they would use as inputs before making a prediction. The predictions obtained from the aforementioned models were compared with predictions obtained by using the arithmetic mean, which is one of the most commonly used indicators. As a result of the aforementioned comparison, it was obtained that the models depending on the number of observations that they used as inputs: 1, 2 or 3; they obtained an R2 of: -0.00287, 0.0611 and 0.0179 respectively.

The predictions obtained, both with the RNA models and with the arithmetic means together with the historical behaviors were used to, through the use of quadratic programming, search for the composition of lower risk portfolios. After carrying out a portfolio management simulation, it was obtained that the portfolios made up from the predictions of the ANN models obtained at the end of the period studied, compared to those made up of the predictions using the arithmetic mean, returns: 5.63% higher , for models that used 1 observation as input; 35.67% higher for those who used 2; and 25.51% for those who used 3. In addition, it was observed that the portfolios made up of the RNA models obtained returns higher than the index, IBEX, by 40.86%, 39.78% and 60.54%, for the models that used 1, 2 and 3 observations as inputs respectively.

The aforementioned results show that the combined use of these tools, ANN and quadratic programming, can offer companies and organizations a significant competitive advantage in the management of their financial assets, allowing more effective decision-making, optimizing the composition of portfolios and maximizing returns.

However, it is important to highlight that the results presented in this paper need a more in-depth study to analyze, among other aspects, the weight that the results of the predictions of the different companies have in the composition of portfolios. For this reason, this work is considered the beginning of a more exhaustive investigation in which: higher quality data must be obtained and the use of various techniques will be contrasted, both to obtain predictions and to find the composition of the portfolio adequate.
