# 3 Conclusións {.unnumbered}

Durante o desenvolvemento deste traballo abordouse a aplicación das redes neuronais artificiais e da programación cuadrática na xestión de carteiras financeiras. A través dunha coidada caracterización das series temporais financeiras, foi posible comprender a importancia de analizar as súas características e patróns para facer previsións máis precisas.

Probáronse diferentes configuracións de modelos de redes neuronais artificiais, compostos pola combinación de capas convolucionais e LSTM, que diferían no número de observacións históricas que utilizarían como entradas antes de facer unha predición. Comparáronse as predicións obtidas a partir dos citados modelos coas predicións obtidas mediante a media aritmética, que é un dos indicadores máis utilizados. Como resultado da citada comparación, obtívose que os modelos en función do número de observacións que utilizaban como entradas: 1, 2 ou 3; obtiveron un R2 de: -0,00287, 0,0611 e 0,0179 respectivamente.

As predicións obtidas, tanto cos modelos de ARN como coas medias aritméticas xunto cos comportamentos históricos foron empregadas para, mediante a programación cuadrática, buscar a composición de carteiras de menor risco. Despois de realizar unha simulación de xestión de carteiras, conseguiuse que as carteiras constituídas a partir das predicións dos modelos ANN obtidas ao final do período estudado, fronte ás compostas polas predicións mediante a media aritmética, producen un rendemento: un 5,63% superior. , para modelos que utilizaron 1 observación como entrada; un 35,67% maior para os que utilizaron 2; e un 25,51% para os que utilizaron 3. Ademais, observouse que as carteiras integradas polos modelos de ARN obtiveron rendementos superiores ao índice, IBEX, nun 40,86%, 39,78% e 60,54%, para os modelos que utilizaron 1, 2 e 3 observacións como entradas respectivamente.

Os resultados mencionados mostran que o uso combinado destas ferramentas, ANN e programación cuadrática, pode ofrecer ás empresas e organizacións unha importante vantaxe competitiva na xestión dos seus activos financeiros, permitindo unha toma de decisións máis eficaz, optimizando a composición das carteiras e maximizando os rendementos.

Non obstante, é importante destacar que os resultados que se presentan neste traballo precisan dun estudo máis profundo para analizar, entre outros aspectos, o peso que teñen na composición das carteiras os resultados das predicións das distintas empresas. Por este motivo, este traballo considérase o inicio dunha investigación máis exhaustiva na que: hai que obter datos de maior calidade e contrastar o uso de diversas técnicas, tanto para obter predicións como para atopar axeitada a composición da carteira.
