# 2.1 Caracterización de series temporais financeiras {.unnumbered}

Este epígrafe divídese en dous subtítulos. No primeiro preséntanse os conceptos fundamentais relacionados coas series temporais, incluíndo as súas características, compoñentes e clasificacións, e establece a súa relación coa análise de series temporais e a previsión, que é o obxectivo deste informe. O segundo subepígrafe afonda nas características dos prezos das accións, partindo dunha descrición xeral e avanzando cara a aspectos máis concretos, así como na importancia da estrutura na que se atopan os datos relativos a estas.

## 2.1.1 Series temporais e as súas características

As series temporais son un tipo de proceso estocástico que se caracteriza por ordenar variables aleatorias segundo o tempo. Isto significa que cada momento está asociado a un valor da variable que depende do azar e que pode cambiar co paso do tempo. Segundo @ruiz2011, un proceso estocástico é "unha colección ou familia de variables aleatorias, ordenadas segundo un subíndice que adoita ser o tempo" (p.01). A análise das series temporais pode ter diferentes finalidades, como describir o comportamento das variables ou prever ou prever os seus valores futuros, o que resulta especialmente relevante para as series financeiras.

A análise de series temporais é unha ferramenta estatística que permite estudar o comportamento dunha variable ao longo do tempo. Non obstante, non existe un consenso único sobre os compoñentes que se deben considerar neste tipo de análises. Algúns autores, como @kocenda2017 e @anderson2017, propoñen que as series temporais poden descompoñerse en tres compoñentes: tendencia, estacionalidade e ruído. Outros autores, como @dodge2008 e @espallargas2012, suxiren que habería que engadir un cuarto compoñente: o ciclo. Por último, hai autores que suxiren que as series temporais poden ter ata cinco compoñentes, son os casos de @IBM2021 e @chirinos2018.

Tendencia: é o patrón de cambio a longo prazo que se observa nunha serie de datos. Pódese definir como a dirección xeral e persistente das variacións da serie ao longo do tempo. Pódese clasificar como positivo (@fig-tend_pos), negativo (@fig-tend_neg) ou nulo (@fig-tend_nul), dependendo de se a serie aumenta, diminúe ou permanece constante a longo prazo. A tendencia pódese identificar mediante análise gráfica ou por métodos estatísticos. Este compoñente é importante para comprender o comportamento histórico e proxectar o futuro dunha serie de datos, é habitual nos distintos criterios mencionados.

Estacionalidade: Tamén chamada variación cíclica regular: Refírese á variación correspondente aos movementos da serie que se producen cada determinado período de tempo, @fig-est_err. Este compoñente é, como a tendencia, habitual nos criterios mencionados. Diferenciando en que aqueles autores que expoñen catro e cinco compoñentes denominan estacionalidade ás variacións periódicas correspondentes a períodos inferiores ou iguais a un ano (como periodicidade diaria, semanal, mensual ou anual), mentres que as variacións periódicas correspondentes a períodos máis longos contemplan. un compoñente chamado variacións cíclicas. Polo tanto, para determinar a estacionalidade dunha serie temporal, é necesario analizalas nun período non inferior a dous anos.

Un compoñente que non se pode explicar polos outros elementos da serie temporal é a variación irregular ou o erro. Este compoñente tamén se coñece como variación aleatoria, ruído ou residual, e móstrase en @fig-est_err. A variación irregular é común nos tres criterios mencionados anteriormente. Algúns autores distinguen entre a variación irregular, que é ocasional e aleatoria, e a variación atípica, que se produce por eventos illados que alteran o comportamento da serie. A variación atípica pódese clasificar en varios tipos: aditiva, innovación, cambio de nivel, transitoria, estacionalidade aditiva e tendencia local.

Unha forma de categorizar as series temporais é segundo o grao de variabilidade que presentan ao longo do tempo Segundo o exposto en @villagarcia2006, é posible distinguir entre series homoscedásticas e heteroscedásticas. As series homoscedásticas son aquelas que manteñen un rango constante de variación, como se mostra en @fig-tend_nul. Pola contra, as series heteroscedásticas son as que cambian o rango de variación, aumentando ou diminuíndo a súa amplitude, como se ilustra nos @fig-tend_pos e @fig-tend_neg.

Un concepto clave na análise de series temporais é o da estacionariedade. Unha serie temporal é estacionaria cando as súas propiedades estatísticas, como a media, a varianza e a covarianza, non cambian co tempo. Isto implica que a serie non presenta tendencia, ciclos ou estacionalidade. Como sinalan @castillo_varela2010, @villavicencio2010 e @ruiz2011, a estacionariedade é unha condición necesaria para poder predicir o comportamento futuro dunha serie temporal mediante técnicas estatísticas. Un exemplo dunha serie temporal estacionaria móstrase en @fig-tend_nul.

As series temporais financeiras presentan heteroscedasticidade, é dicir, varianzas que cambian co tempo. Isto implica que non están estacionarios e que o seu comportamento depende de factores externos. Para verificar a estacionariedade dunha serie temporal pódense empregar diferentes métodos, como o correlograma, que mostra as funcións de autocorrelación e autocorrelación parcial da serie, ou probas de raíces unitarias, como as de Dickey Fuller ou Phillips Perron, que proban o nulo. hipótese de que a serie ten unha raíz unitaria. Estes métodos explícanse con máis detalle en @castillo_varela2010, @villavicencio2010 e @ruiz2011. O @fig-acf_pacf ilustra un exemplo de correlograma para unha serie temporal financeira.

## 2.1.2 Características de prezos

Investir en accións ou en calquera outro activo cotizado na bolsa é unha tarefa complexa e desafiante, que require unha comprensión completa das tendencias e flutuacións do mercado. O núcleo desta comprensión é a capacidade de analizar e interpretar os datos dos prezos do mercado de accións, proporcionando información clave sobre o comportamento dos participantes no mercado e os factores que impulsan os movementos do mercado. A finalidade desta subsección é ofrecer unha visión xeral do entorno de prezos das accións e da súa representación habitual, sinalando os aspectos máis importantes para a aplicación das técnicas que se explorarán nos seguintes apartados.

Como se explica en @cnmvbv, os mercados de accións son mercados organizados onde se negocian accións e outros valores, como renda fixa, warrants, certificados e fondos cotizados en bolsa. En @bmeqe recóllese que, en España, existen catro bolsas de valores tradicionais (Madrid, Barcelona, ​​​​Bilbao e Valencia) que forman parte do holding BME (Bolsas e Mercados Españoles), que tamén integra outros segmentos e negociación, valores dos sistemas de compensación e liquidación. Sendo, segundo explican en @cnmvsibe, o Sistema de Interconexión Bolsa Española (SIBE) é a plataforma que permite a negociación continua e electrónica de todos os valores admitidos a negociación nas catro bolsas españolas.

Como expón @cnmvacci, as accións son valores mobiliarios que representan unha parte proporcional do capital social dunha sociedade anónima, e os seus titulares son socios propietarios da mesma. As accións poden negociarse en bolsas de valores ou noutros mercados secundarios autorizados.

Do exposto en @mitchell20, @pinset21 e @cfi23 pódese concluír que, para explicar o prezo das accións dunha empresa, pódense considerar os seguintes factores:

-   A oferta e a demanda de accións no mercado: se hai máis compradores que vendedores, o prezo subirá e viceversa. Isto depende das expectativas e da confianza dos investidores no futuro da empresa.

-   Cambios na xestión ou produción da empresa: se a empresa mellora a súa eficiencia, a súa rendibilidade ou a súa innovación, o prezo das súas accións poderá aumentar. Pola contra, se a empresa ten problemas internos, perde competitividade ou se ve afectada por crises externas, o prezo pode baixar.

-   A reputación da empresa: se a empresa ten unha boa imaxe pública, está asociada a éxitos ou logros ou recibe boas valoracións dos analistas, o prezo das súas accións pode subir. Pola contra, se a empresa está envolta en escándalos, demandas ou polémicas, ou recibe malas valoracións dos analistas, o prezo pode baixar.

Nos textos @pinset21, @tinvt22 e @cfi23 tamén sinalan a importancia de diferenciar o prezo dunha empresa ou a súa participación do seu valor intrínseco. Poder resumir tendo en conta o que se indica nestes textos e o que se indicou anteriormente que o prezo dunha empresa ou acción é o que compradores e vendedores están dispostos a pagar por ela nun momento determinado, mentres que o valor intrínseco dunha empresa. ou actuación depende en gran medida da metodoloxía empregada para valorar as empresas e dos obxectivos do avaliador.

Unha vez contextualizado de forma xeral o entorno no que se atopan os prezos das accións e explicados algúns dos factores que poden afectalos, a continuación explícase a estrutura na que adoitan aparecer estes datos. Xeralmente, os prezos das accións rexístranse periodicamente (diariamente, semanalmente, mensualmente, anualmente, etc.). rexistrando para cada período o prezo de apertura, o prezo máis alto, o máis baixo, o prezo de peche, o volume e o prezo de peche axustado, consulte @tbl-pre_estruc.

Polo exposto en @barone22, @chen22, @downey22, @hayes21 e @ganti20 pódese entender que:

-   O prezo de apertura é o primeiro prezo ao que se negocia un activo financeiro nunha sesión de negociación. Este prezo pode ser diferente ao prezo de peche da sesión anterior, xa que poden producirse cambios na oferta e na demanda durante o período de peche do mercado. O prezo de apertura adoita indicar o ton ou tendencia do mercado para ese día.

-   O prezo máis alto é o prezo máis alto ao que se negocia un activo financeiro nunha sesión de negociación. Este prezo reflicte o nivel máis alto de interese do comprador para ese activo nese día. O prezo máis alto pode ser un indicador da fortaleza ou debilidade dun activo, así como da súa volatilidade.

-   O prezo máis baixo é o prezo máis baixo ao que se negocia un activo financeiro nunha sesión de negociación. Este prezo reflicte o nivel mínimo de interese dos vendedores por ese activo nese día. O prezo máis baixo pode ser un indicador da presión ou resistencia dun activo, así como da súa volatilidade.

-   O prezo de peche é o último prezo ao que se negocia un activo financeiro nunha sesión de negociación. Este prezo é o que se utiliza para calcular o valor de mercado dese activo ao final do día. O prezo de peche adoita ser o máis importante para os investidores, xa que resume o resultado das operacións do día e mostra a dirección do mercado.

-   O volume é o número de unidades dun activo financeiro negociado nunha sesión de negociación. O volume mostra o nivel de actividade ou liquidez dun mercado ou dun activo. O volume adoita acompañar os movementos de prezos, xa que indica o grao de consenso ou diverxencia entre os participantes no mercado.

-   O prezo de peche axustado é o prezo de peche dun activo financeiro que se modifica para ter en conta eventos como dividendos, escisións, fusións ou adquisicións que afectan ao valor do activo. O prezo de peche axustado permítelle comparar o rendemento histórico dun activo con maior precisión e coherencia.

Polo exposto en @hayes21 e @ganti20, enténdese que a diferenza entre o prezo de peche e o prezo de peche axustado é de grande importancia, xa que o primeiro pode dar unha imaxe distorsionada da evolución dunha acción ao longo do ano. mentres que o segundo reflicte o valor real do stock despois de axustarse polos factores que o alteran.

> administración dunha empresa pode decidir dividir as accións da empresa 3 por 1. Así, as accións en circulación da empresa aumentan por un múltiplo de tres, mentres que o prezo das súas accións divídese por tres. Digamos que unha acción pechou a $ 300 o día antes da súa división. Neste caso, o prezo de peche axústase a $ 100 (\$ 300 dividido por 3) por acción para manter un estándar de comparación consistente. Do mesmo xeito, todos os demais prezos de peche anteriores para esa empresa dividiríanse por tres para obter os prezos de peche axustados. @ganti20

Debido a isto, o prezo de peche axustado é mellor para a aplicación de técnicas de análise de series temporais, xa que permite comparar o comportamento dunha acción ao longo do tempo sen as distorsións provocadas polos eventos corporativos. A serie temporal máis utilizada nos estudos de análise de prezos de mercado é a formada por rendementos calculados a partir do prezo de peche axustado.
