project:
  type: book
  output-dir: ../_book/gal
  post-render: 
    - fix-links.R
  preview: 
    browser: false
    watch-inputs: false
    navigate: false

book:
  cover-image: ../projectlogo.png
  favicon: ../icologo.png
  title: "Traballo Fin de Máster"
  subtitle: "Aplicación das redes neuronais artificiais e da programación cuadrática na xestión de carteiras"
  author: 
    - name: David Díaz Rodríguez
      affiliations:
        - id: udc
          name: Universidade da Coruña 
          city: La Coruña
          state: Galicia
      orcid: https://orcid.org/0000-0002-0927-9795
      email: david.diazr@udc.es
    - name: Xosé Manuel Martínez Filgueira
      affiliations:
        - ref: udc
      orcid: https://orcid.org/0000-0003-2452-4864
      email: xose.martinez@udc.es
  search: true
  repo-url: https://github.com/davidrsch/TFM
  repo-actions: [edit]
  sharing: [twitter]
  page-navigation: true
  sidebar: 
    collapse-level: 1
    pinned: true
    tools:
      - icon: translate
        menu:
          - text: "Español"
            href: ../index.html
          - text: "English"
            href: ../en/index.html
  page-footer: 
    left: |
      Traballo Fin de Máster presentado en
      [![](../feelogo.png){fig-alt="FEE" width=65px}](https://fee.udc.es/)
      [![](../udclogo.png){fig-alt="UDC" width=65px}](https://www.udc.es/)
    center:
      - text: "David Díaz Rodríguez"
    right:
      - icon: linkedin
        url: https://www.linkedin.com/in/david-d-6257951b8/
        aria-label: Linkedin
      - icon: github
        url: https://github.com/davidrsch/TFM/
        aria-label: TFM GitHub
  
  chapters:
    - index.qmd
    - greetings.qmd
    - summarygal.qmd
    - summaryes.qmd
    - summaryen.qmd
    - intro.qmd
    - part: body.qmd
      chapters: 
        - FSandP.qmd
        - ANNinTSF.qmd
        - PC.qmd
        - Data.qmd
        - MandT.qmd
        - Results.qmd
    - conclusions.qmd
    - references.qmd
    - part: "Anexos"
      chapters: 
        - Annex1.qmd
        - Annex2.qmd
        - Annex3.qmd
        - Annex4.qmd
        
bibliography: ../references.bib

format:
  html:
    include-after-body: [my_scripts.html]
    theme: cosmo
    title-block-banner: "#D60D8C"
    fig-cap-location: top
    df-print: paged
    css: ../my_style.css

editor: visual
