# 2.6 Resultado {.unnumbered}

Este epígrafe divídese en dous subtítulos nos que se describen brevemente os resultados obtidos. No primeiro dos subtítulos descríbense e analízanse as predicións. O segundo subtítulo presenta os resultados da aplicación da programación cuadrática para a composición da carteira en función das predicións obtidas.

## 2.6.1 Predicións {#sec-predicciones}

En @sec-A-predicciones pódese atopar unha explicación máis detallada do código utilizado durante o procedemento descrito nesta subsección.

Como se explicou anteriormente, mentres se adestraba o modelo, obtivéronse as predicións. Como se fixo cos modelos de redes neuronais artificiais, as predicións calculáronse para as diferentes observacións utilizando a media aritmética das observacións. Utilizouse a media aritmética porque é unha das medidas máis utilizadas como indicador de posibles comportamentos futuros no estudo das series temporais financeiras.

As predicións avaliaranse calculando o $MSE$ e os valores reais e os $R^2$ dos resultados obtidos polos modelos de redes neuronais artificiais e as medias aritméticas.

Segundo explica @Glen23, o $MSE$ indícalle o preto que está unha recta de regresión dun conxunto de puntos. Faino tomando as distancias dos puntos á recta de regresión (estas distancias son os "erros") e cuadrándoas. O cadrado é necesario para eliminar calquera signo negativo. Tamén dá máis peso ás diferenzas maiores. Chámase erro cadrado medio xa que estás atopando a media dun conxunto de erros. Canto menor sexa o $MSE$, mellor será a previsión, mostrada por @eq-mse tal e como se calculou.

$$
\begin{aligned}
MSE &= \frac{1}{n} * \sum_{i=1}^{n}{(Y_i-\hat{Y_i})^2} \\
\end{aligned}
$$ {#eq-mse}

Onde:

::: margin
$n$: número de observacións
:::

::: margin
$Y_i$: valor real
:::

::: margin
$\hat{Y_i}$: valor esperado
:::

Como explica @Nandakumar20 $R^2$ úsase habitualmente para explicar o bo rendemento dun modelo en comparación coa media global das observacións, @eq-r2:

$$
\begin{aligned}
R^2 &= 1-\frac{SSR}{SST}\\
R^2 &= 1-\frac{\sum_{i=1}^{n}{(Y_i-\hat{Y_i})^2}}{\sum_{i=1}^{n}{(Y_i-\tilde{Y})^2}}\\
\end{aligned}
$$ {#eq-r2}

Onde:

::: margin
$\tilde{Y}$: media aritmética de todas as observacións
:::

Pero este pode ser un indicador inxusto do rendemento dun modelo de regresión xa que se supón que se coñecen todas as observacións sobre as que se calcula unha media, e como se mencionou anteriormente, este non é o caso dos modelos de redes neuronais. metodoloxía de validación avanzada. Debido a isto, modificouse o cálculo de $R^2$, como se fixo noutras investigacións como @NBERw25398, de xeito que o modelo co que se comparan os resultados obtidos polas ANN utilizadas é o que comprenden as medias aritméticas de as observacións anteriores á prevista.

A continuación, describiranse brevemente os diferentes resultados obtidos polos distintos modelos construídos. Cómpre sinalar que, aínda que se propuxeron 3 modelos diferentes de cada un deles, construíronse 10, co obxectivo de estandarizar os resultados obtidos, xa que o proceso de construción e adestramento de redes neuronais contén un factor aleatorio. Polo tanto, os resultados que se describen a continuación son os resultados medios obtidos polos distintos modelos construídos.

### 2.6.1.1 Unha observación

Os resultados obtidos por aqueles modelos que foron adestrados con vectores de entrada que tiñan unha observación de cada serie mostraron, como se ve en @fig-ind_evo_oo, que nos primeiros períodos os modelos presentaban mellores predicións que as obtidas pola media aritmética. . Pódese observar que a eficacia dos modelos en comparación coas medias decae a medida que o modelo avanza no tempo e aprende das novas observacións. Tamén se ve claramente que na maioría dos períodos o $R^2$ deste modelo é negativo. Ademais, obsérvase un pico no $MSE$ do modelo a principios de 2020, que se entende como unha perda de efectividade do modelo, esta perda de efectividade do modelo podería estar relacionada con movementos bruscos do mercado derivados dos efectos económicos. do Covid-19.

A análise previa do comportamento dos indicadores destes modelos por períodos ofrécenos unha visión xeral do desempeño destes modelos, pero dado que os resultados obtidos nas empresas son fundamentais para a composición da carteira, analizaremos agora o comportamento observado en os resultados obtidos polas 20 empresas que presentaron os mellores e peores resultados, a partir dos $R^2$ obtidos como criterio.

Observando os resultados dos indicadores expostos nos @tbl-indicadores, aquelas empresas que presentaron un peor $R^2$ presentan tamén un baixo $MSE$, o que indica que é menos probable que a composición da carteira se vexa alterada polos resultados. obtidos por estas empresas.empresas. Por outra banda, entre as empresas que obtiveron un mellor $R^2$ hai algunhas que obtiveron un $MSE$ elevado acompañado dun $R^2$ superior ao 5%. Isto indica que se poderían xerar diferenzas entre as composicións das carteiras debido ás diferenzas nas previsións e que se trata de empresas que non teñen unha boa $MSE$.

Os resultados descritos no parágrafo anterior son similares para os casos dos modelos construídos con dúas e tres observacións, respectivamente.

### 2.6.1.2 Dúas observacións

Os resultados obtidos por aqueles modelos que foron adestrados con vectores de entrada que tiñan dúas observacións de cada serie, comprobouse, como se ve en @fig-ind_evo_twoo, que nos primeiros períodos os modelos presentaban mellores predicións que as obtidas pola media. . Pódese ver que a eficacia dos modelos en comparación coas medias decae a medida que o modelo avanza no tempo, pero decaen a un ritmo máis lento que aqueles modelos adestrados con vectores de entrada cunha observación. Tamén se ve claramente que o $R^2$ destes modelos ten menos variación que o $R^2$ dos modelos analizados anteriormente, xa que para estes modelos o $R^2$ é positivo na maioría dos períodos. Ademais, como no caso dos modelos analizados anteriormente, tamén se observa un pico no $MSE$ do modelo a principios de 2020.

### 2.6.1.3 Tres observacións

Os resultados obtidos por aqueles modelos que foron adestrados con vectores de entrada que tiñan tres observacións de cada serie, comprobouse, como se ve en @fig-ind_evo_threeo, que nos primeiros períodos os modelos presentaban mellores predicións que as obtidas pola media. . Pódese ver que a eficacia dos modelos en comparación coas medias decae a medida que o modelo avanza no tempo, pero decaen a un ritmo máis lento que aqueles modelos adestrados con vectores de entrada cunha observación. Obsérvase claramente que o R2 destes modelos presenta unha maior variación que o R2 dos modelos analizados anteriormente, observando como esta variación diminúe para aquelas predicións posteriores a 2015. Estes modelos, como os primeiros, presentaron un R2 negativo na maioría deles. . dos períodos. Ademais, como nos casos anteriores, tamén se observa un pico no $MSE$ do modelo a principios de 2020.

## 2.6.2 Composición de carteiras {#sec-cc}

Pódese atopar unha explicación máis detallada do código utilizado durante o procedemento descrito nesta subsección en @sec-A-cc.

Neste subepígrafe descríbense os resultados obtidos tras aplicar a programación cuadrática para determinar a composición da carteira. Esta, así como as previsións, fíxose período a período co obxectivo de emular unha situación real na que as técnicas se aplicasen no seu conxunto. Polo tanto, a presente análise céntrase no comportamento observado ao utilizar os distintos modelos e na comparación destes resultados cos obtidos co uso de medias.

Como se pode ver en @fig-pf_evo_oo, as carteiras feitas a partir das predicións obtidas polos modelos de redes neuronais que tiñan unha observación xeralmente obtiveron mellores resultados que as carteiras feitas a partir das predicións usando a media. Obsérvase que ambos grupos de carteiras presentaron unha rendibilidade inferior á do índice, IBEX, no período comprendido entre 2009 e 2016.

Ao realizar a análise do comportamento dos rendementos obtidos polos modelos con dúas observacións de entrada, @fig-pf_evo_twoo, obsérvase: o comportamento dos rendementos obtidos polos distintos modelos varía menos que os analizados anteriormente; Neste caso e contrariamente ao caso anterior, os rendementos seguen sendo similares no período comprendido entre 2009 e 2016; e aínda que o resultado final dista moito do resultado obtido polas medias, é inferior ao obtido polos modelos anteriores, sendo este último debido a que a avaliación dos modelos neste caso comeza nun período anterior aos de modelos analizados anteriormente.

Observando os resultados obtidos polos últimos modelos, @fig-pf_evo_threeo, obsérvase: unha distribución de rendementos superior aos adestrados con dúas observacións pero inferior aos adestrados cunha observación; obsérvase que os rendementos comezan a superar os do índice despois de 2013 en lugar de 2016 como en anos anteriores; e tamén se observa que os rendementos dos modelos de ARN son superiores aos das medias e tamén constitúen os máximos rendementos obtidos entre as distintas estruturas dos modelos de ARN.
